server {
    # ============================================================
    # 基础监听配置
    # ============================================================
    listen 80;
    server_name 117.72.60.13;

    # ============================================================
    # 网站根目录
    # ============================================================

    # 设置 HTTP 服务的根目录
    root /usr/share/nginx/html;
    index index.html;

    # ============================================================
    # 字符编码
    # ============================================================
    charset utf-8;

    # ============================================================
    # 目录浏览
    # ============================================================

    # 开启目录列表功能
    # 当用户访问一个目录，而该目录中不存在 index.html
    # 等默认首页文件时，Nginx 会自动生成目录列表。
    # 可以看到目录和文件列表。
    autoindex on;

    # on：
    #   显示精确字节数
    # off：
    #   使用更加易读的单位显示
    # 对文件服务器来说，off 更适合人类阅读。
    autoindex_exact_size off;



    # on：
    #   使用服务器所在系统的本地时间
    # off：
    #   使用 UTC 时间
    autoindex_localtime on;


    # 设置目录列表的输出格式
    # html：
    #   生成 HTML 格式的目录列表，
    #   浏览器可以直接显示并点击文件/目录。
    # Nginx 还支持 json、xml 等格式（具体取决于版本/编译选项），
    # 但普通浏览器文件浏览一般使用 html 即可。
    autoindex_format html;


    # ============================================================
    # 请求处理
    # ============================================================

    location / {

        # 检查请求对应的文件或目录是否存在
        # $uri：
        #   当前请求的 URI 路径
        # $uri/：
        #   按目录进行检查
        # =404：
        #   如果文件和目录都不存在，则返回 HTTP 404
        # 例如：
        # 请求：
        #   /test.txt
        # 如果：
        #   /usr/share/nginx/html/test.txt
        # 存在，则正常返回文件。
        # 请求：
        #   /docs/
        # 如果：
        #   /usr/share/nginx/html/docs/
        # 存在，则进入该目录处理。
        # 如果请求：
        #   /abc.txt
        # 而文件不存在，则直接返回 404。
        try_files $uri $uri/ =404;
    }


    # ============================================================
    # 日志
    # ============================================================
    # HTTP 请求访问日志
    # 记录客户端访问了什么 URL、返回什么状态码、
    # 请求来源 IP、User-Agent 等信息。
    access_log /var/log/nginx/access.log;


    # Nginx 错误日志
    #
    # 用于记录 Nginx 运行过程中出现的错误，
    # 例如文件权限问题、配置问题、连接异常等。
    error_log /var/log/nginx/error.log;
}