
user  nginx;					#进程以nginx用户运行
worker_processes  auto;				#工作进程数	自动调节

error_log  /var/log/nginx/error.log notice;	#日志存放地址,并且只存放notice及以上等级的日志
pid        /run/nginx.pid;			#主进程pid存放地址


events {
    worker_connections  1024;			#设置每个worker进程的并发数
}


http {
    include       /etc/nginx/mime.types;	#文件类型映射表,nginx会根据映射表给请求添加响应头,例如Content-Type:text/css,浏览器根据响应头进行css样式渲染,如果是text/html则会进行网页渲染
    default_type  application/octet-stream;	#当接受类型不存在文件类型映射表中,nginx会给请求添加请求头Content-Type: application/octet-stream,浏览器就会进行下载

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
		#设置名叫main的日志存储格式:
		# 192.168.1.100 - - [16/八月/2026:14:32:18 +0800] "GET /index.html HTTP/1.1" '
		# 200 2048 "https://www.baidu.com/" '
		# "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
		#192.168.1.100 的用户，在 2026-08-16 14:32:18 通过 Chrome 浏览器从百度跳转过来,访问了 /index.html，返回 200 成功，页面大小 2048 字节（约 2KB）

    access_log  /var/log/nginx/access.log  main; #使用上面设置的main格式进行日志写入

    sendfile        off;			 #绕过用户态直接在内核态传输,提高静态文件传输速度,但是在代理情况sendfile会导致部分头信息处理异常,需要关闭
    #tcp_nopush     on;				 #开启后:提高单个网络包的体积,减少网络开销,实现性能优化,提高大体积包的下载速度,配合sendfile使用	

    keepalive_timeout  65;			 

    #gzip  on;					 #开启后压缩文本响应（HTML/CSS/JS），减少传输体积

    include /etc/nginx/conf.d/*.conf;		 
}
